### PR TITLE
Admin dashboard

### PR DESCRIPTION
**Pull request by clburns107**
Trying to get administrate to effin work...

### CODE REVIEW

**Comment by clburns107** [comment]
The given instructions for administrate on heroku are incorrect.  There is no dashboard manifest file to alter.  So I ran rails generate administrate:routes in my playground.  Now its telling me that the route is wrong.  

error: ArgumentError (Invalid route name, already in use: 'admin_root'
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:

also im even more confused because the routes documentation doesnt look like my routes file.  So if i could get some explanation bout how that works and what that does and maybe some insite on how to make administrate even work to begin with that would be awesome!

**Comment by clburns107** [comment]
It looks like this video assumes that all of the dashboards have been created for me... Which they have not.  Only one has been created for theaters and users and plays dashboards do not exist. I need to understand how to create the other ones and how to link them together? Do i literally just create a new dashboard file and copy whats in theaters?

**Comment by halfghaninne** [comment]
This is the most helpful thing I've found so far... https://github.com/thoughtbot/administrate/issues/182 Shows that it's possible to manually create dashboards for models. Does not address the issues with dashboard manifest (which I am also having).

**Comment by halfghaninne** [comment]
Looks like when you ran `rails generate administrate:routes` you [duplicated some of your work](https://github.com/clburns107/rails-playground/blob/admin_dashboard/config/routes.rb#L12-L16) in your **config/routes.rb** file. Try deleting that duplication, restarting the rails server, and see how things work.

**Comment by halfghaninne** [comment]
[This line](https://github.com/clburns107/rails-playground/blob/admin_dashboard/config/routes.rb#L8) in the `namespace` block just tells administrate what default view to pull up when a user goes to **localhost:3000/admin**

**Pull request merged**
